#
# github action for preparing an R environment with
# a couple of packages (including ggplot2)
# and running the R script to generate the
# day of week chart
#

name: Weekday

on:
#  schedule: # 03:00 JST == 18:00 UTC
#    - cron: "0 18 * * *"
#  workflow_dispatch:
  workflow_call:
    inputs:
      github_pat:
        description: 'GITHUB PAT'
        required: true
        default: ${{ github.token }}
      username:
        description: 'Github username'
        required: true
 #       default: '${{ github.repository_owner }}'
      repository:
        description: 'Repository'
        required: true

      
permissions: write-all  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ inputs.github_pat }}
      R_KEEP_PKG_SOURCE: yes
    name: generate chart
    steps:
     - name: install curl
       run: sudo apt-get install -y libcurl4-openssl-dev

     - name: Set up R
       uses: r-lib/actions/setup-r@v2
       with:
        r-version: 4.x
        use-public-rspm: true

     - name: Install dependencies
       run: Rscript -e "install.packages(c('curl','gh','dplyr','ggplot2','viridis'))"
       
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
          repository: brandmaier/weekdaychart
          ref: main  # specify the branch 
        
     - name: Generate graph
       env:
          GITHUB_TOKEN: ${{ inputs.github_pat }}
          USERNAME: ${{ inputs.username }}
          REPOSITORY: ${{ inputs.repository }}
       run: |
          Rscript chart.R
